root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  gravitee-cloud/guides/hybrid/install-on-docker: gravitee-cloud/guides/hybrid
  gravitee-cloud/guides/hybrid/install-on-kubernetes: gravitee-cloud/guides/hybrid
